# Generated by Django 3.2.4 on 2022-05-21 12:05

import versatileimagefield.fields
from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(
                        max_length=80, unique=True, verbose_name="email address"
                    ),
                ),
                ("username", models.CharField(max_length=32, unique=True)),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="late joined"),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "profile_image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        default=accounts.models.get_default_profile_image,
                        height_field="height",
                        null=True,
                        upload_to="user-profile-images",
                        verbose_name="Profile picture",
                        width_field="width",
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Profile Image Height"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Profile Image Width"
                    ),
                ),
            ],
            options={
                "db_table": "Account",
                "ordering": ("username",),
            },
        ),
    ]
