# Generated by Django 3.2.4 on 2021-08-12 10:54

import accounts.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=accounts.models.get_default_profile_image, force_format=None, keep_meta=True, null=True, quality=75, size=[50, 50], upload_to=accounts.models.get_profile_image_filepath, verbose_name='Profile picture'),
        ),
    ]
