# Generated by Django 3.2.4 on 2022-02-05 10:14

import accounts.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default=accounts.models.get_default_profile_image, null=True, upload_to=accounts.models.get_profile_image_filepath, verbose_name='Profile picture'),
        ),
    ]
