# Generated by Django 3.2.4 on 2022-02-05 10:42

import accounts.models
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220205_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='account',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default=accounts.models.get_default_profile_image, height_field='height', null=True, upload_to=accounts.models.get_profile_image_filepath, verbose_name='Profile picture', width_field='width'),
        ),
    ]
