# Generated by Django 3.2.4 on 2022-02-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220205_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ppoi',
        ),
        migrations.AlterField(
            model_name='account',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Profile Image Height'),
        ),
        migrations.AlterField(
            model_name='account',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Profile Image Width'),
        ),
    ]
