# Generated by Django 3.2.4 on 2022-02-06 08:45

import accounts.models
from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220205_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default=accounts.models.get_default_profile_image, height_field='height', null=True, upload_to='user-profile-images', verbose_name='Profile picture', width_field='width'),
        ),
    ]
