# Generated by Django 3.2.4 on 2022-05-21 12:05

import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=450, verbose_name="Category description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "Category",
                "unique_together": {("title", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Tag")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "Tag",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=250,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "Published"), ("draft", "Draft")],
                        default="draft",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("publication_date", models.DateTimeField(verbose_name="Created")),
                (
                    "picture",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        height_field="height",
                        null=True,
                        upload_to="blog-uploads/%Y/",
                        verbose_name="Picture as thumbnail",
                        width_field="width",
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Profile Image Height"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Profile Image Width"
                    ),
                ),
                (
                    "picture_description",
                    models.CharField(
                        max_length=127, verbose_name="description of the image"
                    ),
                ),
                (
                    "post_excerpt",
                    ckeditor.fields.RichTextField(verbose_name="post excerpt"),
                ),
                (
                    "post_content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="post content"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Is the post feature or not?"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        default="Anonymous", max_length=64, verbose_name="Created by"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.category",
                        verbose_name="Category",
                    ),
                ),
                ("tags", models.ManyToManyField(to="blog.Tag")),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "db_table": "Post",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127, verbose_name="Name")),
                ("email", models.CharField(max_length=256, verbose_name="Email")),
                ("body", models.TextField(verbose_name="Comment")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "db_table": "Comment",
                "ordering": ["created_date"],
            },
        ),
    ]
