# Generated by Django 3.2.4 on 2021-10-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210812_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='The Worlds of devices, applications &amp; Next Gen. Evolution', max_length=450, verbose_name='Category description'),
            preserve_default=False,
        ),
    ]
