# Generated by Django 3.2.4 on 2021-11-13 10:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is the post feature or not?'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_excerpt',
            field=ckeditor.fields.RichTextField(default='this is the text except', verbose_name='post excerpt'),
            preserve_default=False,
        ),
    ]
