# Generated by Django 3.2.4 on 2022-02-06 13:43

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20211113_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Profile Image Height'),
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Profile Image Width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='blog-uploads/%Y/', verbose_name='Picture as thumbnail', width_field='width'),
        ),
    ]
